### PR TITLE
Add all-contributors bot via: https://allcontributors.org/docs/en/bot…

### PR DESCRIPTION
**Pull request by CSRedRat**
Add all-contributors bot via: https://allcontributors.org/docs/en/bot/installation

GitHub repo: https://github.com/all-contributors/all-contributors

## Add to contributors

Comment on an issue or pull request with:
@all-contributors please add @CSRedRat for code, infra, tests, ideas, maintenance, platform, mentoring and example ✨

### CODE REVIEW

**Comment by CSRedRat** [comment]
@all-contributors please add @CSRedRat for code, infra, tests, ideas, maintenance, platform, mentoring and example ✨

**Comment by CSRedRat** [comment]
@all-contributors please add @CSRedRat for code, infra, tests, ideas, maintenance, platform, mentoring and example ✨🔭

**Comment by CSRedRat** [comment]
@all-contributors please add @CSRedRat for code

**Comment by CSRedRat** [comment]
@all-contributors please add @CSRedRat for code

**Comment by KirstieJane** [comment]
Hi @CSRedRat - are you looking for help with the all contributors bot? Can you link the .allcontributorsrc file? The bot is super sensitive to spelling mistakes so have a read through to check that the words are exactly as in the emoji key (https://allcontributors.org/docs/en/emoji-key)

**Comment by CSRedRat** [comment]
@KirstieJane https://github.com/CSRedRat/topalias/blob/master/.all-contributorsrc
I try with .all-contributorsrc and without and have message from bot "We had trouble processing your request. Please try again later."
I add contributors from cli, but want give from bot. Thx.

**Comment by KirstieJane** [comment]
What happens if you delete lines 26 - 35 ? I think they're optional and there might be an error in there somewhere?

**Comment by CSRedRat** [comment]
@KirstieJane Thank you feedback. I delete lines for bot and generate contributors from cli: https://allcontributors.org/docs/en/cli/installation

**Comment by CSRedRat** [comment]
@KirstieJane in #20 with clean  .allcontributorsrc generated by cli allcontributors bot does not matter can't add contributor

**Pull request merged**
